language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "danielkraft"
    token:
      secure: "c8669d0716a3159d6ef5f61a061fc57c33d279a7"

jdk:
  - openjdk8

script:
  - SONAR_SKIP=$(if [ "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_REPO_SLUG = 'DanielKraft/illumi-code-ddd' ]; then echo "false"; else echo "true"; fi)
  - if [ $SONAR_SKIP = "false" ]; then git fetch --unshallow --quiet; fi
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
