package illumi.code.ddd.model;

public enum DDDType {
	ENTITY, 
	VALUE_OBJECT, 
	AGGREGATE_ROOT, 
	FACTORY, 
	REPOSITORY, 
	SERVICE, 
	APPLICATION_SERVICE,
	INFRASTRUCTURE,
	MODULE, 
	DOMAIN_EVENT
}
