package illumi.code.ddd.model;

public enum DDDType {
	ENTITY, 
	VALUE_OBJECT, 
	AGGREGATE_ROOT, 
	FACTORY, 
	REPOSITORY, 
	SERVICE, 
	APPLICATION_SERVICE, 
	INFRASTRUCTUR,
	MODULE, 
	CONTROLLER , 
	DOMAIN_EVENT
}
