micronaut:
   application:
      name: illumi-code-ddd
   server:
      port: 8040
      cors:
         enabled: true
      idle-timeout: 20m
neo4j:
   uri: bolt://localhost
   embedded:
      ephemeral: true
    
